### ISSUE TITLE
Add OAuth 2.0 support

### ISSUE THREAD

**Issue by stark-chase** [kshehadeh/ts-confluence-client#10]
Hello :)
Is it possible to add OAuth 2.0 support to this client? As I understand it only requires to add an access token field in the ConfConnectionInfo type and add it to the request if exists.

Another way to enable it is to let the user give it's own AxiosInstance to the Resource class, and then he can control the requests that is being sent.

I can also help with this issue if needed :)

Thanks!

**Comment by kshehadeh** [comment]
Hi Tomer,

Sure I can take a look at that.  It might be a few days before I can get to
it though.  Feel free to PR though if you need it sooner.

**Comment by stark-chase** [comment]
Great, I created PR #11

**Comment by stark-chase** [comment]
Changes were merged. closing the issue.
